### ISSUE TITLE
how can I get the value of input arguments

### ISSUE THREAD

**Issue by zhaochl** [fisherman/getopts#13]
for example
getopts.sh -d 2012-01-01
how I can get value the date to a variable

**Comment by jbucaran** [comment]
@zhaochl Hi! 

```
getopts -d 2012-01-01
```

has the following output:

```
d 2012-01-01
```

So, what you do is read the key (first column) and value (second column) into variables or arrays like this:


```fish
getopts -d 2012-01-01 | read -l key value
```

To confirm:

```fish
echo $key # d
echo $value # 2012-01-01
```

Cheers! 👋
